sudo: false

# Choose a lightweight base image; we provide our own tools.
language: c

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'


install:
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
# - stack --no-terminal -j1 --install-ghc build --only-dependencies --fast
  - stack --no-terminal -j1 --install-ghc build aeson-1.0.2.1 aeson-better-errors-0.9.1.0 aeson-pretty-0.8.2 alex-3.2.1 async-2.1.1 attoparsec-0.13.1.0 blaze-builder-0.4.0.2 blaze-html-0.8.1.3 blaze-markup-0.7.1.1 bower-json-1.0.0.1 boxes-0.1.4 case-insensitive-1.2.0.8 comonad-5 conduit-1.2.9 contravariant-1.4 cookie-0.4.2.1 css-text-0.1.2.2 data-default-0.7.1.1 data-default-instances-old-locale-0.0.1 distributive-0.5.2 edit-distance-0.2.2.1 exceptions-0.8.3 fast-logger-2.4.10 fsnotify-0.2.1 Glob-0.7.14 hashable-1.2.5.0 hinotify-0.3.9 http-date-0.0.6.1 http-types-0.9.1 iproute-1.7.1 language-javascript-0.6.0.9 lifted-base-0.2.3.10 mime-types-0.1.0.7 mmorph-1.0.9 monad-control-1.0.1.0 network-uri-2.6.1.0 old-locale-1.0.0.7 old-time-1.1.0.3 optparse-applicative-0.13.2.0 parallel-3.2.1.0 parsec-3.1.11 pattern-arrows-0.0.2 pem-0.2.2 pipes-4.3.2 prelude-extras-0.4.0.3 primitive-0.6.1.0 protolude-0.1.10 psqueues-0.2.2.3 QuickCheck-2.9.2 random-1.1 reflection-2.1.2 regex-base-0.93.2 regex-compat-0.95.1 regex-posix-0.95.2 regex-tdfa-1.2.2 resourcet-1.1.9 safe-0.3.14 scientific-0.3.4.10 semigroups-0.18.2 simple-sendfile-0.2.25 socks-0.5.5 sourcemap-0.1.6 spdx-0.2.1.0 split-0.2.3.1 StateVar-1.1.0.4 stm-2.4.4.1 stm-chans-3.0.0.4 stringsearch-0.3.6.6 syb-0.6 tagged-0.8.5 tagsoup-0.14.1 text-1.2.2.1 tf-random-0.5 time-locale-compat-0.1.1.3 transformers-base-0.4.4 transformers-compat-0.5.1.4 uniplate-1.6.12 unix-compat-0.4.3.1 unix-time-0.3.7 unordered-containers-0.2.7.2 utf8-string-1.0.1.1 vault-0.3.0.6 vector-0.11.0.0 void-0.7.1

script:
  - echo Skipping
# - stack --no-terminal -j1 build --fast

notifications:
  email: true

before_deploy:
  - mkdir bundle
  - cp `stack path --dist-dir`/build/trypurescript/trypurescript bundle/
  - cp LICENSE bundle/
  - tar czf trypurescript.tar.gz -C bundle/ .

deploy:
  provider: releases
  api_key: $RELEASE_KEY
  file: trypurescript.tar.gz
  skip_cleanup: true
  on:
    tags: true
